language: objective-c

osx_image: xcode7.3

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update
- pod install

script:
    xcodebuild -workspace PlantInfo.xcworkspace -scheme PlantInfo -sdk iphonesimulator build