# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    ENV['DEVELOPER_DIR'] = '/Applications/Xcode_7.app/Contents/Developer'
  end

  lane :build do
    increment_build_number
    sigh
    gym(scheme: “PlantInfo”, use_legacy_build_api: false) 
  end

  lane :screenshots do
    snapshot
  end

end



